Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productId { get; set; }
        public string productname { get; set; }
        public string productdetails { get; set; }
        public string productprice { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using First.Models.Account;
using First.Models;
using System.Web.Security;


namespace First.Controllers
{
    public class HomeController : Controller
    {


        public ActionResult Payment() 
        {
            return View();
        }

        public ActionResult Product()
        {
            using (Database1Entities1 db = new Database1Entities1())
            {
                return View(db.Products.ToList());
            }
        }


        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Product product)
        {
            try
            {
                using (Database1Entities1 db=new Database1Entities1())
                {
                    db.Products.Add(product);
                    db.SaveChanges();

                }
                return RedirectToAction("Product");

            }
            catch 
            {
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            //string email = Request.Cookies["user_email"].Value.ToString();
            using (Database1Entities2 db1 = new Database1Entities2())
            { 
            
            
            }
            using (Database1Entities1 db = new Database1Entities1())
            {
                return View(db.Products.Where(x => x.productId == id).FirstOrDefault());
            }
        }




        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Signup(User modal)
        {
            try
            {
                using (Database1Entities db = new Database1Entities())
                {
                    db.Users.Add(modal);
                    db.SaveChanges();

                }
                return RedirectToAction("Login");

            }
            catch
            {
                return View();
            }
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(User user)
        {
            using (var context=new Database1Entities())
            {
                bool isValid = context.Users.Any(x => x.Email == user.Email && x.Password == user.Password);
                if (isValid)
                {
                    Response.Cookies.Add(new HttpCookie("user_email", user.Email.ToString()));
                    //FormsAuthentication.SetAuthCookie(user.Name, false);
                    return RedirectToAction("Product");
                }
                ModelState.AddModelError("", "Wrong combination of email and password");
                return View();
            }
                
        }

    }
}

Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace First.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using First.Models;

namespace First.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product/
        public ActionResult Index()
        {   using (Database1Entities1 db = new Database1Entities1())
            {
                return View(db.Products.ToList());
            }
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Product/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using First.Models;
using First.Models.Account;

namespace First.Controllers
{
    public class SignupController : Controller
    {
        // GET: Signup
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login( User user)
        {
            
                return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Create.cshtml
@model First.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.productname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productdetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productdetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productdetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productprice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productprice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productprice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Home/Details.cshtml
@model First.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details of Items</h2>

<div>
    <h4>Product</h4>
    <hr />
    <table class="dl-horizontal bg-info">
        <tr class="m-3">
            <td class="bg-primary">
                @*@Html.DisplayNameFor(model => model.productname)*@
                Product Name:
            </td>

            <td>
                &nbsp;&nbsp;  @Html.DisplayFor(model => model.productname)
            </td>
        </tr>
        <tr class="m-3">
            <td class="bg-primary" align="left">
                @*@Html.DisplayNameFor(model => model.productdetails)*@
                Product Details:  
            </td>

            <td>
                &nbsp;&nbsp;  @Html.DisplayFor(model => model.productdetails)
            </td>
        </tr>
        <tr class="m-3">
        <td class="bg-primary" align="left">
            @*@Html.DisplayNameFor(model => model.productprice)*@ 
            Product Price: 
        </td>

        <td>
            &nbsp;&nbsp; Rs: @Html.DisplayFor(model => model.productprice)
        </td>
        </tr>

    </table>
    <hr />
    <a href="~/Home/Payment" class="btn btn-outline-primary center-block">

        Buy
    </a>
    
</div>
<br/>
<br/>
<p>
   
    @Html.ActionLink("Back to ProductList", "Product")
</p>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.net</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Home/Login.cshtml
@model First.Models.Account.User

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { type="email", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { type="password", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Sigup", "Signup")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Home/Payment.cshtml
@*@{
        ViewBag.Title = "Payment";
    }

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>paymennt method</title>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css'>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Krona+One&display=swap" rel="stylesheet">
        <link href="~/Content/StyleSheet1.css" rel="stylesheet" />
    </head>
    <body>
        <div class="heading">
            <h1>Payment Method</h1>
        </div>
        <div class="header">
            <h1>Please select your payment option</h1>

            <div class="radio-container">
                <input type="radio" id="windows" name="os" />
                <label for="windows">credit card and debit card</label>



                <br>
                <button id="open">Add card</button>

            </div>
        </div>

        <div class="modal-container" id="modal_container">
            <div class="modal">
                <div class="wrapper">
                    <div class="payment">
                        <div class="payment-logo">
                            <p>p</p>
                        </div>


                        <h2>Payment Gateway</h2>
                        <div class="form">
                            <div class="card space icon-relative">
                                <label class="label">Card holder:</label>
                                <input type="text" class="input" placeholder="Coding Market">
                                <i class="fas fa-user"></i>
                            </div>
                            <div class="card space icon-relative">
                                <label class="label">Card number:</label>
                                <input type="text" class="input" data-mask="0000 0000 0000 0000" placeholder="Card Number">
                                <i class="far fa-credit-card"></i>
                            </div>
                            <div class="card-grp space">
                                <div class="card-item icon-relative">
                                    <label class="label">Expiry date:</label>
                                    <input type="text" name="expiry-data" class="input" data-mask="00 / 00" placeholder="00 / 00">
                                    <i class="far fa-calendar-alt"></i>
                                </div>
                                <div class="card-item icon-relative">
                                    <label class="label">CVC:</label>
                                    <input type="text" class="input" data-mask="000" placeholder="000">
                                    <i class="fas fa-lock"></i>
                                </div>
                            </div>

                            <div class="btn">
                                Pay
                            </div>
                            <br />
                            <button id="close">
                                Back
                            </button>


                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="~/Scripts/JavaScript.js"></script>
       <script>

           const open = document.getElementById('open');
           const close = document.getElementById('close');
           const modal = document.getElementById('modal_container');

           open.addEventListener('click', () => {
               modal.classList.add('show');
           });


           close.addEventListener('click', () => {
               modal.classList.remove('show');
           });
       </script>
    </body>
    </html>*@

<script src="https://code.jquery.com/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<h2> Payment Gateway</h2>
<br />
<br />
<div class="container-fluid bg-info">
    <h3> Payment Method</h3>
    <hr />

    <input type="radio" id="windows" name="os" />
    <label for="windows">Credit Card and Debit Card</label>
    <br />
    <button type="button" class="btn btn-outline-primary btn-lg" data-toggle="modal" data-target="#myModal">Add card</button>
    <hr />
    <input type="radio" id="windows" name="os" />
    <label for="windows">Cash on Delivery(COD)</label>
    <br/>
    <button type="button" class="btn btn-outline-primary btn-lg" onclick="submit()">COD</button>
    <br />

    <!-- Modal -->
    <div class="modal fade bootstrap" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header bg-primary">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Enter your card details:</h4>
                </div>
                <div class="modal-body bg-primary">

                    <div class="form">

                        <input type="text" maxlength="16" minlength="16" data-mask="0000 0000 0000 0000" placeholder="Card Number" class="form-control form-control-lg m-3">
                        
                        <input type="text" data-mask="00 / 00" id="inputExpDate" minlength="5"maxlength="5" placeholder="MM / YY" class="form-control form-control-lg m-3">
                        <input type="text" data-mask="000" maxlength="3"minlength="3" placeholder="cvv" class="form-control form-control-lg m-3">

                    </div>

                </div>
                <div class="modal-footer bg-primary">
                    <button type="button" class="btn btn-outline-primary" data-dismiss="modal" onclick="submit()">Submit</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script >
    function submit() {
        alert("Thankyou for ordering ");
    };

</script>

Views/Home/Product.cshtml
@model IEnumerable<First.Models.Product>

@{
    ViewBag.Title = "Product";
}

<h2>Product</h2>




<style>
    .card:hover {

        box-shadow:-1px 9px 40px -12px #808080;
    }
</style>

<div class="row">
@foreach(var item in Model)
{
    <div class="card w-25 m-3">
        <img src = "" class="card-img-top"/>
        <div class="card-body">
            <div class="card-title">
                <h2 id="name" value="@item.productname">@Html.DisplayFor(modelItem => item.productname)</h2>
            </div>
            <div class="card-text">
                <p >
                    @Html.DisplayFor(  modelItem => item.productdetails)
                </p>
                <p>
                    <b>
                          Rs: @Html.DisplayFor(modelItem => item.productprice)
                    </b>
                </p>
            </div>
            <div class="btn btn-outline-primary">
                @Html.ActionLink("Add to cart", "Details", new { id = item.productId })

            </div>
            

            <input type="button" value="click me" onclick="submit(@item.productId, @item.productprice,'@item.productname')" />



        </div>


</div >
}

</div >
<script>

    function submit(id,price, name) {
            
        debugger
        
        var obj = {
            Id:id,
            Price:price,

        }
        submitform(obj);

    };

    function submitform(obj) {
        $.ajax({
        url:/home/})

    }
</script>

Views/Home/Signup.cshtml
@model First.Models.Account.User

@{
    ViewBag.Title = "Signup";
}

<h2>Signup</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Signup" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Login", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}